Support ids
nioinnovation/topic-grapher.js pull request #4
Opened 2018-04-03 17:14 UTC by aaronranard

Change name to be id and v`2.0.0` will always require an id

2018-04-10 17:42 UTC, tlugger requested changes

2018-04-10 17:42 UTC, tlugger commented on src/index.js
>        name,
Looks like we can remove name here since we never use it afterwords.

2018-04-10 17:42 UTC, tlugger commented on src/index.js
> +      mapping.reduce((rest, { id, mapping: block }) => ({
I'm getting `no-shadow` linter errors for this line.

2018-04-10 17:42 UTC, tlugger commented on src/index.js
> +    const resolveId = id => (mappings[id] || id);
Same for this line. Not sure why because we never change the value of `id` it looks like...

2018-04-11 15:37 UTC, aaronranard commented
Addressed linter issues

2018-04-11 20:23 UTC, tlugger approved these changes

2018-04-11 20:23 UTC, merged